_BASE_: "base.yaml"
MODEL:
  LOSS_TYPE: 'FrankensteinLoss'
  OUT_CHANNELS: 1
  IN_CHANNELS: 14
OUTPUT_BASE_DIR: ('logs/')
DATASETS:
  TRAIN: ("/storage/yonk/urban_extraction_twocities/train/",)
  TEST: ("/storage/yonk/urban_extraction_twocities/test/",)
  INFERENCE: ("/storage/yonk/debug_new/test/",)
  USE_CLAHE_VARI: False
TRAINER:
  LR: 0.0001
  BATCH_SIZE: 1
  EDGE_LOSS_SCALE: 20
DATALOADER:
  NUM_WORKER: 0
  S1_FEATURES: ['VV_asc_mean', 'VH_asc_mean', 'VV_desc_mean', 'VH_desc_mean']
  S2_FEATURES: ['Blue_median', 'Green_median', 'Red_median', 'RedEdge1_median','RedEdge2_median','RedEdge3_median', 'NIR_median','RedEdge4_median', 'SWIR1_median', 'SWIR2_median']
  LABEL: 's1s2_allbands_twocities'
AUGMENTATION:
  # Random cropping of the images
  CROP_TYPE: 'none'
  IMAGE_OVERSAMPLING_TYPE: 'simple'
  RANDOM_FLIP_ROTATE: False