_BASE_: "base.yaml"
MODEL:
  LOSS_TYPE: 'FrankensteinEdgeLoss'
  OUT_CHANNELS: 1
  IN_CHANNELS: 3
  USE_ATTENTION: True
OUTPUT_BASE_DIR: ('logs/')
DATASETS:
  TRAIN: ("/storage/yonk/debug_new/train/",)
  TEST: ("/storage/yonk/debug_new/test/",)
  INFERENCE: ("/storage/yonk/debug_new/test/",)
  USE_CLAHE_VARI: True
TRAINER:
  LR: 0.001
  BATCH_SIZE: 8
  EDGE_LOSS_SCALE: 20
DATALOADER:
  NUM_WORKER: 0
AUGMENTATION:
  # Random cropping of the images
  CROP_TYPE: 'importance'
  CROP_SIZE: 256
  IMAGE_OVERSAMPLING_TYPE: 'simple'
