_BASE_: "frankenstein_oversample_3conv.yaml"
THRESH: 0.52
MODEL:
  LOSS_TYPE: 'FrankensteinLoss'
  OUT_CHANNELS: 1
  BLOCK_TYPE: 'Triple'
  LAST_LAYER_RESIDUAL: True
  TOPOLOGY: [128, 128, 256, 512,]
AUGMENTATION:
  # Random cropping of the images
  CROP_TYPE: 'importance'
  CROP_SIZE: 256
  IMAGE_OVERSAMPLING_TYPE: 'simple'

