_BASE_: "unet_dice.yaml"
THRESH: 0.52
MODEL:
  LOSS_TYPE: 'FrankensteinLoss'
  OUT_CHANNELS: 1
  BLOCK_TYPE: 'Triple'
  TOPOLOGY: [64, 256, 512, 1024,]
AUGMENTATION:
  # Random cropping of the images
  CROP_TYPE: 'importance'
  CROP_SIZE: 256
  IMAGE_OVERSAMPLING_TYPE: 'simple'

